In [24]:
import numpy as np 
from src import nocode
import torch
import torch.nn as nn

In [25]:
# Here is our config file

path="demo/demo_config.yaml"

In [26]:
# parse, build and load the model in a single line of code 
model = nocode.Build(path)

Empty layer added for args:  {'tensors': ['conv3', 'conv5'], 'dim': 1}


In [27]:
# What if I want to use pretrained models? 
# How to prove that the results from a model built 
# with nocode.ai would give the same results as a proper PT
# model? 
# Here, we have the weights from a PyTorch model and well verify
# whether they give the same result or not...

wts_path = "demo/test.pth"

#load the weights!
model.load_weights(wts_path)

In [28]:
# Lets run an one's tensor 
ex = torch.ones((1, 3, 10, 10))

ans_model = model(ex)
print(f"ans_model.shape: [{ans_model.shape}]")

ans_model.shape: [torch.Size([1, 128, 8, 8])]


In [36]:
# Lets define a PyTorch model and the load the same weights 
# to check whether we get the same results!

class PTModel(nn.Module):
    def __init__(self):
        super(PTModel, self).__init__()
        self.conv1 = nn.Conv2d(3, 64, 3, 1)
        self.relu1 = nn.ReLU()
        self.conv2 = nn.Conv2d(64, 64, 1, 1)
        self.relu2 = nn.ReLU()
        self.conv3 = nn.Conv2d(64, 64, 1, 1)
        self.conv4 = nn.Conv2d(64, 64, 1, 1)
        self.relu3 = nn.ReLU()
        self.conv5 = nn.Conv2d(64, 64, 1, 1)
        self.relu4 = nn.ReLU()
    
    def forward(self, x):
        x = self.relu1(self.conv1(x))
        x1 = self.conv3(self.relu2(self.conv2(x)))
        x = self.conv5(self.relu3(self.conv4(x)))
        x = torch.cat([x1, x], dim=1)
        return self.relu4(x)

In [37]:
# lets instantiate the model and load the common wts


pt_model = PTModel()

pt_model.load_state_dict(torch.load(wts_path))


<All keys matched successfully>

In [41]:
# lets run our ones tensor through

ex = torch.ones((1, 3, 10, 10))
pt_ans = pt_model(ex)
print(f"pt_ans.shape: {pt_ans.shape}")

pt_ans.shape: torch.Size([1, 128, 8, 8])


In [42]:
# lets print and check one of their channels 
print(ans_model[0, 1])
print(pt_ans[0, 1])

tensor([[0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124]],
       grad_fn=<SelectBackward>)
tensor([[0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
        [0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124, 0.0124],
    

In [44]:
print(ans_model[0, 2])
print(pt_ans[0, 2])

tensor([[0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581]],
       grad_fn=<SelectBackward>)
tensor([[0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
        [0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581, 0.0581],
    